<a href="https://colab.research.google.com/github/Saurabh77-99/Pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cu121


### intro to tensors

tensors are way to represent multidimensional numeric data

Pytorch tensors are created using `torch.Tensor()`

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
#scalar has no dimensions it is single number
scalar .ndim

0

In [ ]:
# get tensor back as a python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim # dimension is number of pair of closing square brackets

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[0], matrix[1]

(tensor([7, 8]), tensor([ 9, 10]))

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
# Tensor
tensor = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Random tensors are imp bcoz the way many neural networks learn is that they start with tensors full of random numbers and then adjust random numbers to better represent the data.

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# create a random tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1466, 0.1525, 0.8465, 0.3172],
        [0.8699, 0.2751, 0.0225, 0.0447],
        [0.8685, 0.7513, 0.9451, 0.7931]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # color channels ,height,width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

if you are working with random tensor and you want to mask out all numbers in the column and multipy it by your target tensor

In [ ]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range() might get deprecated message , use torch.arange()
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### tensor datatypes

tensor datatypes is one of the 3 big errors you will run into with pytorch and deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not right device

Precision in computing

In [ ]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what datatype is tensor? (ex:Float32 or float16)
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor , can use `tensor.dtype`
2. Tensors not right shape - to get shape from tensor , can use `tensor.shape`
3. Tensors not right device - to get device from a tensor , can use `tensor.device`

In [ ]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2259, 0.0484, 0.6709, 0.6548],
        [0.5157, 0.4191, 0.3737, 0.5447],
        [0.4513, 0.2640, 0.4908, 0.3076]])

In [ ]:
some_tensor.size() ,some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
# finding details about tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2259, 0.0484, 0.6709, 0.6548],
        [0.5157, 0.4191, 0.3737, 0.5447],
        [0.4513, 0.2640, 0.4908, 0.3076]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [ ]:
# create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# multiplying tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# try out pytorch inbuilt functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing matrix multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satsify:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [ ]:
torch.matmul(torch.rand(4,2),torch.rand(2,3))

tensor([[0.3997, 0.6131, 0.3357],
        [0.4661, 0.9299, 0.4580],
        [0.3859, 0.9493, 0.4347],
        [0.4479, 0.7698, 0.4018]])

In [ ]:
# Element wise
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplicatin
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# matmul by hand
1*1 + 2*2 + 3*3

14

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
%%time
# matrix multiplication by hand
value = 0
for i in range(len(tensor)):
    value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.87 ms, sys: 0 ns, total: 1.87 ms
Wall time: 6.71 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 82 µs, sys: 0 ns, total: 82 µs
Wall time: 85.8 µs


tensor(14)

## One of the most common errors in DL :Shape errors

In [ ]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues,we can manipulate the shape of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of given tensor.

In [ ]:
tensor_B.T , tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# the matrix multiplication works when tensor_B is transposed.
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")

print(f"Multiplying: {tensor_A.shape} * {tensor_B.shape} <- inner dimensions")
print(f"Output:\n")
output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"Output shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([3, 2]) <- inner dimensions
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Output shape: torch.Size([3, 3])


### finding min , max , mean , sum etc (Tensor aggregation)

In [ ]:
x = torch.arange(1,100,10)
x , x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
# find the min
torch.min(x) , x.min()

(tensor(1), tensor(1))

In [ ]:
# find the max
torch.max(x) , x.max()

(tensor(91), tensor(91))

In [ ]:
# find the mean
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# find the sum
torch.sum(x) , x.sum()

(tensor(460), tensor(460))

### Finding positional min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# find the position in tensor that has the min value with argmin() -> returns index position of target tensor where the min value occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
# find the position in tensor that has the max value with argmin() -> returns index position of target tensor where the max value occurs
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

## reshaping , stacking , squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory
* Stacking - combine multiple tensors on top of each other (vstack) or side by side(hstack)
* Squeeze - removes all `1` dimensions from tensor
* Unsqueeze - add a `1` dimension to target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in certain way

In [ ]:
import torch
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped , x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1,9)
z , z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# stack tensors on top
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])
New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at speific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}\n")

# add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"New target: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New target: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at speific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}\n")

# add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"New target: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New target: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [ ]:
# torch.permute - rearranges the dimension of a target tensor in specify order
x_original = torch.rand(size=(224,224,3)) # height,width,color_channels(image tensor)

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shift axis 0->1 , 1->2 , 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0] = 10
x_original[0,0,0],x_permuted[0,0,0]

(tensor(10.), tensor(10.))

## Indexing (selecting data from tensors)

indexing with ytorch is similar to indexing with Numpy

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[0,2,2]

tensor(9)

In [ ]:
# you can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of 0 dimension and 1st dimensions but only 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimensions and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
x[:,:,2]

tensor([[3, 6, 9]])

## Pytorch Tensors and Numpy

Numpy is a popular scientific python numerical compile library.

and because of this, Pytorch has functionality to interact with it.

* Data in Numpy , want in pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensir -> Numpy -> `torch.Tensor.numpy()`

In [ ]:
# Numpy array to tensor
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
# warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype

torch.float32

In [ ]:
torch.arange(1.0,8.0).dtype

torch.float32

In [ ]:
# change the value of array , what will this do to `tensor`?
array = array + 1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# change the tensor , what happens to `numpy_tensor`?
tensor = tensor + 1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of this data -> again -> again -> again...`

To reduce the randomness in neural networks and pytorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness

In [ ]:
torch.rand(3,3)

tensor([[0.2297, 0.4927, 0.5240],
        [0.5303, 0.5538, 0.8350],
        [0.8117, 0.1544, 0.5576]])

In [ ]:
import torch

# create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(f"Random tensor A:\n {random_tensor_A}\n")
print(f"Random tensor B:\n {random_tensor_B}\n")
print(f"Does random tensor A equal random tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Random tensor A:
 tensor([[0.9063, 0.7562, 0.2114, 0.4534],
        [0.7177, 0.7596, 0.9584, 0.1025],
        [0.8312, 0.3245, 0.3988, 0.4185]])

Random tensor B:
 tensor([[0.7548, 0.4215, 0.0114, 0.8849],
        [0.4421, 0.7509, 0.6411, 0.6282],
        [0.4944, 0.7212, 0.1125, 0.2450]])

Does random tensor A equal random tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
# Let's make some random but reprudicible tensors
import torch

# set random seed -> it only works for one block
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(f"Random tensor C:\n {random_tensor_C}\n")
print(f"Random tensor D:\n {random_tensor_D}\n")
print(f"Does random tensor C equal random tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Random tensor C:
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Random tensor D:
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does random tensor C equal random tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Running tensors and pytorch objects on the GPU's and faster computations

GPUs = faster computations in numbers, CUDA + Nvidia hardware working  behind the access to make everything

from sre_constants import GROUPREF_UNI_IGNORE
### 1.Getting a GPU

1. Easiest to use Google Colab for a free GPU
2. Buying your own
3. Use cloud computing - GCP, AWS

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


import torch
torch.cuda.is_available()

# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

# count number of device
torch.cuda.device_count()

In [ ]:
# move tensor to GPU -> will work when GPU is connected
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

NameError: name 'device' is not defined